export const authActions = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  REGISTRATION: "REGISTRATION"
};

export const financeActions = {
  FETCH_FINANCES: "FETCH_FINANCES",
  SET_FINANCE_ID: "SET_FINANCE_ID",

  FETCH_FINANCE_DETAIL: "FETCH_FINANCE_DETAIL",
  SAVED_FINANCE_DETAIL: "SAVED_FINANCE_DETAIL"
};
